Refs #17247 Add checkbox for excluding offer from cosmetic pricing

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 # Check for built files, and yell at user if not
 
+
 # Find source files that are marked as modified
 sources=`git status -s | grep 'M.*client\/src\/.*'`
 
@@ -12,3 +13,13 @@ if [ -n "$sources" ] &&  [ -z "$built" ]; then
     echo "Please compile static files before committing."
     exit 1
 fi
+
+# Check JS formatting
+pushd ./client/ &> /dev/null
+yarn prettier --check ./ || echo "Error: Format JS/TS code with prettier before committing."
+popd &> /dev/null
+
+# Check Python formatting
+pushd ./server/ &> /dev/null
+black --check ./ || echo "Error: Format Python code with black before committing."
+popd &> /dev/null
